### PR TITLE
Update storage, aks, and servicebus library version

### PR DESCRIPTION
**Pull request by yuwzho**

### CODE REVIEW

**Comment by mattclay** [comment]
@yuwzho Why is this update needed?

**Comment by yuwzho** [comment]
@mattclay Because the sanity test fails with message cannot find the latest API version model. 

https://github.com/ansible/ansible/pull/49702#issuecomment-452332049

**Comment by mattclay** [comment]
@yuwzho That validate-modules error indicates there is something wrong with the way the imports are being handled. I have an idea what it could be. I'll take a closer look at it tomorrow.

**Comment by yuwzho** [comment]
@mattclay Thanks in advance

**Comment by mattclay** [comment]
@yuwzho I added a comment to https://github.com/ansible/ansible/pull/49702#discussion_r252010986 explaining how to resolve the issue.

I'm closing this PR since the changes here only hide the issue, rather than fixing it.

**Pull request closed without merging**
